# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-03 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20190319_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
