FROM python:2

ENV PYTHONUNBUFFERED 1
ENV COUNTRY_APP=south_africa

RUN apt-get update && \
    apt-get install -y binutils \
                       libffi-dev \
                       libjpeg-dev \
                       libpq-dev \
                       libxml2-dev \
                       libxslt1-dev \
                       libproj-dev \
                       gdal-bin \
                       python-dev \
                       python-gdal \
                       ruby-bundler \
                       ruby2.3-dev \
                       yui-compressor \
                       zlib1g-dev

RUN mkdir /app
COPY requirements.txt /app/
RUN pip install -r /app/requirements.txt

COPY . /app/
# Set WORKDIR after installing, so that src dir isn't created then overwritten
# by development mount
WORKDIR /app

RUN bundle install

ENTRYPOINT ["bin/entrypoint.sh"]
