# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-12-11 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0016_auto_20201119_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationhistory',
            options={'ordering': ['date_changed'], 'verbose_name_plural': 'organisation histories'},
        ),
        migrations.AlterField(
            model_name='organisationhistory',
            name='new_organisation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='org_history_new', to='core.Organisation'),
        )
    ]
